version: "3.9"

services:
  mysql:
    container_name: cronjob-shedlock-mysql
    image: mysql:${MYSQL_VERSION:-8.0.36}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    env_file:
      - ./../.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5

volumes:
  mysql-data:
    driver: local
