version: "3.9"

services:
  cronjob-shedlock:
    container_name: cronjob-shedlock-api
    image: 01092002/cronjob-shedlock:1.0.0
    ports:
      - "6969:6969"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: ${MYSQL_HOST_PROD}
      MYSQL_PORT: ${MYSQL_PORT_PROD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_PROD}
      MYSQL_USER: ${MYSQL_USER_PROD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_PROD}
