version: "3.9"

services:
  cronjob-shedlock:
    container_name: cronjob-shedlock-api
    image: 01092002/cronjob-shedlock:latest
    ports:
      - "6969:6969"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env
