apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjob-shedlock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronjob-shedlock
  template:
    metadata:
      labels:
        app: cronjob-shedlock
    spec:
      containers:
        - name: cronjob-shedlock
          image: 01092002/cronjob-shedlock:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: cronjob-shedlock-configmap
          ports:
            - containerPort: 6969
              name: cronjob-port
---
apiVersion: v1
kind: Service
metadata:
  name: cronjob-shedlock-service
spec:
  type: LoadBalancer
  selector:
    app: cronjob-shedlock
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: cronjob-port